### ISSUE TITLE
Sidekiq Cron Support

### ISSUE THREAD

**Issue by jediofthecode** [TrestleAdmin/trestle-sidekiq#1]
Currently it is not clear if it's possible, or how, you can use sidekiq-cron with the sidekiq webui for trestle. I am wondering if you have done this before, and if it's possible to integrate  it, rather than having to fork the gem and hardcode it into the routes.

**Comment by spohlenz** [comment]
I would suggest adding the following lines to your `config/initializers/sidekiq.rb` (create if necessary):

```ruby
require "sidekiq/web"
require "sidekiq/cron/web"
```

This seems to handle the cron extension correctly.

**Comment by jediofthecode** [comment]
This worked perfectly, thanks!
